[project]
name = "mcp-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-google-genai>=2.1.8",
    "mcp-use>=1.3.6",
    "mcp[cli]>=1.12.0",
]
